import { GET_POST_DETAIL_FORM_WORKFLOW_RESOURCE_ID } from "../../constants";

export const GET_POST_DETAIL_FORM_WORKFLOW_END_WORKFLOW_NODE_RESOURCE_ID = `${GET_POST_DETAIL_FORM_WORKFLOW_RESOURCE_ID}-end-workflow-node`;
