import { GET_POST_DETAIL_FORM_WORKFLOW_RESOURCE_ID } from "../../constants";

export const GET_POST_DETAIL_FORM_WORKFLOW_FIND_AND_UPDATE_WORKFLOW_NODE_RESOURCE_ID = `${GET_POST_DETAIL_FORM_WORKFLOW_RESOURCE_ID}-find-and-update-workflow-node`;
